name: Update Dist

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dist:
    name: Update Dist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run
        run: npm run bundle

      - name: Push Changes
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -a -m "Update dist"
          git push
